---
title: "Project dataset"
output: html_document
date: "2023-12-02"
---
## Packages
```{r}
library(tidymodels)
library(randomForest)
library(dplyr)
library(ggplot2)
library(caret)
library(pROC)
library(glmnet)
```

## Data Cleaning and Merging
```{r}
# Read the datasets
player_awards <- read.csv("Player Award Shares.csv")
advanced_stats <- read.csv("Advanced.csv")

# Check the unique values in the key columns
print(unique(advanced_stats$player))
print(unique(player_awards$player))
print(unique(advanced_stats$season))
print(unique(player_awards$season))

# Merge the datasets
combined_data <- merge(advanced_stats, player_awards, by = c("season", "player"))


# Rename 'tm.x' to 'team' in combined_data
combined_data <- combined_data %>%
  rename(team = tm.x)

team_abbrev <- read.csv("Team Abbrev.csv")
team_abbrev <- team_abbrev %>%
  rename(team_name = team, team = abbreviation)

# Merge combined_data with team_abbrev
combined_data <- merge(combined_data, team_abbrev, by = c("season", "team"))
combined_data <- combined_data %>%
  select(-c(age.y, tm.y, seas_id.y, player_id.y, lg.y))
colnames(combined_data) <- tolower(colnames(combined_data))

# Inspect the first few rows of the merged data
head(combined_data)

combined_data$dpoy_winner <- with(combined_data, as.factor(award == "dpoy" & winner == TRUE))

combined_data <- combined_data %>%
  filter(!is.na(season) & !is.na(award) & !is.na(winner) & 
         !is.na(dws) & !is.na(blk_percent) & !is.na(stl_percent) & 
         !is.na(trb_percent) & !is.na(dbpm) & !is.na(playoffs))

combined_data <- combined_data %>%
  select(-birth_year)

# Check the updated dataset
combined_data <- combined_data %>% filter(award == "dpoy")
head(combined_data)


seasons_2015to2022 <- combined_data %>%
  filter(season <= 2022)
seasons_2023 <- combined_data %>%
  filter(season == 2023)

seasons_2015to2022 %>% arrange(desc(dpoy_winner))

set.seed(445)
colnames(seasons_2015to2022)

seasons_2015to2022_x<- data.matrix(data.frame(seasons_2015to2022 %>% select(-dpoy_winner) , stringsAsFactors = FALSE))

seasons_2015to2022_y<- data.matrix(data.frame(seasons_2015to2022 %>% select(dpoy_winner) , stringsAsFactors = FALSE))


seasons_2023_x<- data.matrix(data.frame(seasons_2023 %>% select(-dpoy_winner) , stringsAsFactors = FALSE))

seasons_2023_y<- data.matrix(data.frame(seasons_2023 %>% select(dpoy_winner) , stringsAsFactors = FALSE))
```